name: Build and Deploy Client Static Web App to AWS S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/weather-client/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create client env file
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > src/weather-client/.env

      - name: Build client app
        run: |
          cd src/weather-client
          npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-north-1"
          SOURCE_DIR: "/src/weather-client/build"
